# Generated by Django 5.0.4 on 2024-07-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.IntegerField(blank=True, default=1, verbose_name='Venue Owner'),
        ),
    ]
